name: Test

on:
  pull_request:
  push:
    branches:
      - master

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - ruby-version: '3.1'
            experimental: true
          - ruby-version: '3.2'
            experimental: false
          - ruby-version: '3.3'
            experimental: false
          - ruby-version: '3.4'
            experimental: false
          - ruby-version: '4.0'
            experimental: true

    continue-on-error: ${{ matrix.experimental }}

    steps:
      - uses: actions/checkout@v6

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1.316.0
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true

      - name: Run tests
        run: bundle exec rake

      - name: Upload artifact
        if: always()
        uses: actions/upload-artifact@v7.0.1
        with:
          name: test-results-${{ matrix.ruby-version }}
          path: test-results
          if-no-files-found: ignore
