name: Test

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false 
      matrix:
        ruby-version: ['2.4', '2.7', '3.0', '3.1.3']
    steps:
    - uses: actions/checkout@v4
    - uses: actions/cache@v4.2.0
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile') }}
        restore-keys: |
          ${{ runner.os }}-gem-
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1.207.0
      with:
        ruby-version: ${{ matrix.ruby-version }}
    - name: Install dependencies
      run: bundle check || bundle install --jobs=4 --retry=3 --path vendor/bundle
    - name: Run tests
      run: bundle exec rake
    - name: Upload artifact
      uses: actions/upload-artifact@v4.6.0
      with:
        name: test-results-${{ matrix.ruby-version }}
        path: test-results
